name: clean space

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: config/feeds.conf.default
  CONFIG_FILE: config/.config
  DIY_P1_SH: config/diy-part1.sh
  DIY_P2_SH: config/diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Display Current Time
      run: |
        echo "Current time:"
        date

    - name: Set timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        date

    - name: Display Beijing Time
      run: |
        echo "Current time in Beijing:"
        date
        
    - name: Clean up server space
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/
        rm -rf $(ls . | grep -v "^bin$" | xargs) 2>/dev/null
        df -hT ${PWD}
        
    - name: Check space usage
      if: (!cancelled())
      run: df -hT
