name: Delete All Workflow Runs

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'GitHub Token'
        required: true

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete Workflow Runs
      run: |
        TOKEN=$1
        REPO_API_URL=$(jq -r .repository.url $GITHUB_EVENT_PATH)
        WORKFLOWS_API_URL="$REPO_API_URL/actions/runs"
        
        # Get all workflow runs
        RUNS=$(curl -s -H "Authorization: token $TOKEN" $WORKFLOWS_API_URL)
        
        # Delete each run
        for run_id in $(echo $RUNS | jq -r '.workflow_runs[].id'); do
          curl -s -X DELETE -H "Authorization: token $TOKEN" "$WORKFLOWS_API_URL/$run_id"
          echo "Deleted workflow run: $run_id"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
